import { Link } from 'react-router-dom';
import { Minus, Plus, Trash2, Mail, ArrowLeft } from 'lucide-react';
import { products } from '../data';
import { getProductCopy } from '../productTranslations';
import { useCart } from '../cart';
import { useI18n } from '../i18n';
import './Cart.css';

const cartTranslations = {
  EN: { cart:'YOUR CART',selection:'YOUR SELECTION.',size:'SIZE',remove:'REMOVE',empty:'Your cart is empty.',continue:'CONTINUE SHOPPING',ready:'READY TO REQUEST?',item:'item',items:'items',requestIntro:'Check your selection above, then send your request. We will confirm availability and the next steps by e-mail.',requestButton:'REQUEST VIA E-MAIL',how:'HOW IT WORKS',how1:'ADeriva is a small independent brand, and we are still building our store. We do not have a full online checkout or payment system in place yet.',how2:'Instead, we use a simple request system. When you click REQUEST VIA E-MAIL, your selection is prepared in an e-mail for us. We will then check availability, confirm the details with you and arrange payment and delivery directly.',how3:'This also means we can answer questions, help with sizes and make sure everything is right before you place your order.',emailHello:'Hello, I would like to request the following products:',emailSize:'Size',emailQuantity:'Quantity',emailName:'Name',emailCountry:'Country',emailComments:'Additional comments:' },
  ES: { cart:'TU CARRITO',selection:'TU SELECCIÓN.',size:'TALLA',remove:'ELIMINAR',empty:'Tu carrito está vacío.',continue:'CONTINUAR COMPRANDO',ready:'¿LISTO PARA SOLICITAR?',item:'artículo',items:'artículos',requestIntro:'Revisa tu selección y envíanos tu solicitud. Confirmaremos la disponibilidad y los siguientes pasos por email.',requestButton:'SOLICITAR POR EMAIL',how:'CÓMO FUNCIONA',how1:'ADeriva es una pequeña marca independiente y todavía estamos construyendo nuestra tienda. Por el momento no contamos con un sistema completo de compra y pago online.',how2:'En su lugar, utilizamos un sencillo sistema de solicitud. Cuando haces clic en SOLICITAR POR EMAIL, tu selección se prepara en un email para nosotros. Comprobaremos la disponibilidad, confirmaremos los detalles contigo y gestionaremos directamente el pago y la entrega.',how3:'Esto también nos permite responder a tus preguntas, ayudarte con las tallas y asegurarnos de que todo está correcto antes de realizar el pedido.',emailHello:'Hola, me gustaría solicitar los siguientes productos:',emailSize:'Talla',emailQuantity:'Cantidad',emailName:'Nombre',emailCountry:'País',emailComments:'Comentarios adicionales:' },
  FR: { cart:'VOTRE PANIER',selection:'VOTRE SÉLECTION.',size:'TAILLE',remove:'SUPPRIMER',empty:'Votre panier est vide.',continue:'CONTINUER LES ACHATS',ready:'PRÊT À COMMANDER ?',item:'article',items:'articles',requestIntro:'Vérifiez votre sélection ci-dessus, puis envoyez-nous votre demande. Nous confirmerons la disponibilité et les prochaines étapes par e-mail.',requestButton:'COMMANDER PAR E-MAIL',how:'COMMENT ÇA MARCHE',how1:'ADeriva est une petite marque indépendante et nous sommes encore en train de construire notre boutique. Nous ne disposons pas encore d’un système complet de paiement et de commande en ligne.',how2:'À la place, nous utilisons un système de demande simple. Lorsque vous cliquez sur COMMANDER PAR E-MAIL, votre sélection est préparée dans un e-mail pour nous. Nous vérifierons la disponibilité, confirmerons les détails avec vous et organiserons directement le paiement et la livraison.',how3:'Cela nous permet également de répondre à vos questions, de vous aider avec les tailles et de nous assurer que tout est correct avant votre commande.',emailHello:'Bonjour, je souhaiterais demander les produits suivants :',emailSize:'Taille',emailQuantity:'Quantité',emailName:'Nom',emailCountry:'Pays',emailComments:'Commentaires supplémentaires :' },
  DE: { cart:'DEIN WARENKORB',selection:'DEINE AUSWAHL.',size:'GRÖSSE',remove:'ENTFERNEN',empty:'Dein Warenkorb ist leer.',continue:'WEITER SHOPPEN',ready:'BEREIT ZUR ANFRAGE?',item:'Artikel',items:'Artikel',requestIntro:'Überprüfe deine Auswahl und sende anschließend deine Anfrage. Wir bestätigen die Verfügbarkeit und die nächsten Schritte per E-Mail.',requestButton:'PER E-MAIL ANFRAGEN',how:'SO FUNKTIONIERT ES',how1:'ADeriva ist eine kleine unabhängige Marke und wir bauen unseren Shop noch auf. Ein vollständiges Online-Bestell- und Zahlungssystem gibt es derzeit noch nicht.',how2:'Stattdessen nutzen wir ein einfaches Anfrage-System. Wenn du auf PER E-MAIL ANFRAGEN klickst, wird deine Auswahl für uns in einer E-Mail vorbereitet. Wir prüfen die Verfügbarkeit, bestätigen die Details mit dir und organisieren Zahlung und Lieferung direkt.',how3:'So können wir auch Fragen beantworten, bei der Größenwahl helfen und sicherstellen, dass alles stimmt, bevor du deine Bestellung aufgibst.',emailHello:'Hallo, ich möchte folgende Produkte anfragen:',emailSize:'Größe',emailQuantity:'Menge',emailName:'Name',emailCountry:'Land',emailComments:'Zusätzliche Kommentare:' }
} as const;

export function Cart() {
  const { language } = useI18n();
  const copy = cartTranslations[language];
  const { items, updateQuantity, removeItem } = useCart();
  const entries = items.map(item => ({ item, product: products[item.productIndex] })).filter(e => e.product);
  const totalItems = items.reduce((sum, item) => sum + item.quantity, 0);
  const emailBody = `${copy.emailHello}\n\n${entries.map(({ item }) => { const p = getProductCopy(item.productIndex, language); return `• ${p.name} — ${copy.emailSize}: ${item.size} — ${copy.emailQuantity}: ${item.quantity}`; }).join('\n')}\n\n${copy.emailName}:\n${copy.emailCountry}:\n${copy.emailComments}\n`;

  return <section className="shop-section cart-page">
    <div className="section-heading"><div><p className="eyebrow">{copy.cart}</p><h1>{copy.selection}</h1></div></div>
    {entries.length === 0 ? <div className="cart-empty"><p>{copy.empty}</p><Link className="button button-red" to="/"><ArrowLeft size={16}/> {copy.continue}</Link></div> : <>
      <div className="cart-items">{entries.map(({ item, product }) => { const localized = getProductCopy(item.productIndex, language); return <article className="cart-item" key={`${item.productIndex}-${item.size}`}>
        <Link className="cart-item-image" to={`/product/${item.productIndex}`}><img src={product.image} alt={localized.name}/></Link>
        <div className="cart-item-info"><p className="eyebrow">{localized.category}</p><h3>{localized.name}</h3><div className="cart-size">{copy.size} <strong>{item.size}</strong></div><div className="cart-controls"><div className="cart-quantity"><button type="button" onClick={() => updateQuantity(item.productIndex, item.size, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={14}/></button><span>{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.productIndex, item.size, item.quantity + 1)} aria-label="Increase quantity"><Plus size={14}/></button></div><button className="cart-remove" type="button" onClick={() => removeItem(item.productIndex, item.size)}><Trash2 size={16}/> {copy.remove}</button></div></div>
      </article>; })}</div>
      <div className="cart-request"><div className="cart-request-copy"><p className="eyebrow">{copy.ready}</p><h3>{totalItems} {totalItems === 1 ? copy.item : copy.items}</h3><p>{copy.requestIntro}</p></div><a className="cart-email-button" href={`mailto:aderiva.indierock@gmail.com?subject=${encodeURIComponent(`ADeriva Store — ${copy.requestButton.toLowerCase()}`)}&body=${encodeURIComponent(emailBody)}`}><Mail size={20}/><span>{copy.requestButton}</span></a></div>
      <div className="cart-how-it-works"><p className="eyebrow">{copy.how}</p><p>{copy.how1}</p><p>{copy.how2}</p><p>{copy.how3}</p></div>
    </>}
  </section>;
}
