import { useEffect, useMemo, useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { products, heroImages } from '../data';
import { ProductCard } from '../components/ProductCard';
import { useI18n } from '../i18n';

type Props = { category: string; onAddToCart: (productIndex: number, size: string, quantity: number) => void; liked: number[]; toggleLiked: (index: number) => void };
const copy = { EN: { UNISEX: ['FOR EVERY BODY', 'Unisex', 'pieces.', "Cuts that don't ask who you are. Made to be worn, borrowed and lived in."], MEN: ['MEN', 'Menswear,', 'loud.', 'Overshirts, heavy tees and accessories built for the road and the pit.'], WOMEN: ['WOMEN', 'Womenswear,', 'restless.', 'Silhouettes that move with you — from the first chord to the last train home.'], COLLECTIONS: ['CURATED CAPSULES', 'The', 'collections.', "Limited capsules and seasonal drops. Once they're gone, they're gone."] }, ES: { UNISEX: ['PARA TODOS', 'Prendas', 'unisex.', 'Cortes que no preguntan quién eres. Para llevar, compartir y vivir con ellos.'], MEN: ['HOMBRE', 'Ropa de hombre,', 'sin ruido.', 'Sobrecamisas, camisetas gruesas y accesorios para la carretera y el pogo.'], WOMEN: ['MUJER', 'Ropa de mujer,', 'inquieta.', 'Siluetas que se mueven contigo, desde el primer acorde hasta el último tren a casa.'], COLLECTIONS: ['CÁPSULAS CURADAS', 'Las', 'colecciones.', 'Cápsulas limitadas y lanzamientos de temporada. Cuando se acaban, se acaban.'] }, FR: { UNISEX: ['POUR TOUT LE MONDE', 'Pièces', 'unisexe.', 'Des coupes qui ne demandent pas qui vous êtes. À porter, partager et vivre.'], MEN: ['HOMMES', 'Vestiaire homme,', 'libre.', 'Surchemises, t-shirts épais et accessoires pensés pour la route et la fosse.'], WOMEN: ['FEMMES', 'Vestiaire femme,', 'libre.', 'Des silhouettes qui bougent avec vous, du premier accord au dernier train.'], COLLECTIONS: ['CAPSULES CURATÉES', 'Les', 'collections.', 'Des capsules limitées et des drops saisonniers. Une fois partis, ils le sont pour de bon.'] }, DE: { UNISEX: ['FÜR ALLE', 'Unisex-', 'Teile.', 'Schnitte, die nicht fragen, wer du bist. Zum Tragen, Teilen und Leben.'], MEN: ['HERREN', 'Menswear,', 'laut.', 'Overshirts, schwere T-Shirts und Accessoires für Straße und Moshpit.'], WOMEN: ['DAMEN', 'Womenswear,', 'unruhig.', 'Silhouetten, die sich mit dir bewegen — vom ersten Akkord bis zum letzten Zug nach Hause.'], COLLECTIONS: ['KURATIERTE KAPSELN', 'Die', 'Kollektionen.', 'Limitierte Kapseln und saisonale Drops. Wenn sie weg sind, sind sie weg.'] } } as const;
const productFilters = ['ALL ITEMS', 'UPPER CLOTHES', 'BOTTOMS', 'ACCESSORIES'] as const;
const filterCopy = { EN: ['ALL ITEMS','UPPER CLOTHES','BOTTOMS','ACCESSORIES'], ES: ['TODOS','PARTE DE ARRIBA','PANTALONES','ACCESORIOS'], FR: ['TOUS','HAUTS','BAS','ACCESSOIRES'], DE: ['ALLE','OBERTEILE','HOSEN','ACCESSOIRES'] } as const;
type ProductFilter = (typeof productFilters)[number];
export function Category({ category, onAddToCart, liked, toggleLiked }: Props) {
  const { language, t } = useI18n(); const c = copy[language][category as keyof typeof copy.EN] ?? copy[language].UNISEX; const labels = filterCopy[language]; const [activeFilter, setActiveFilter] = useState<ProductFilter>('ALL ITEMS'); const showFilters = category !== 'COLLECTIONS';
  useEffect(() => { setActiveFilter('ALL ITEMS'); }, [category]);
  const visibleProducts = useMemo(() => products.map((product, index) => ({ product, index })).filter(({ product }) => product.category === category).filter(({ product }) => !showFilters || activeFilter === 'ALL ITEMS' || product.productType === activeFilter), [activeFilter, category, showFilters]);
  return <><section className="page-hero page-hero-image" style={{ backgroundImage: `url(${heroImages[category.toLowerCase() as keyof typeof heroImages] || heroImages.unisex})` }}><div className="page-hero-overlay" /><div className="page-hero-content"><p className="eyebrow">{c[0]}</p><h1>{c[1]} <em>{c[2]}</em></h1><p className="page-hero-text">{c[3]}</p></div></section><section className="shop-section"><div className="section-heading"><div><p className="eyebrow">{category} / {t.currentFrequency}</p><h2>{t.freshTracks}</h2></div></div>{showFilters && <div className="product-filters" role="tablist" aria-label="Filter products">{productFilters.map((filter, i) => <button key={filter} className={activeFilter === filter ? 'active' : ''} onClick={() => setActiveFilter(filter)} role="tab" aria-selected={activeFilter === filter}>{labels[i]}</button>)}</div>}{visibleProducts.length > 0 ? <div className="product-grid">{visibleProducts.map(({ product, index }) => <ProductCard key={product.name} product={product} index={index} liked={liked.includes(index)} onLike={() => toggleLiked(index)} onAdd={onAddToCart} />)}</div> : <div className="empty-state"><p>NO {labels[productFilters.indexOf(activeFilter)].toLowerCase()} AVAILABLE YET.</p><button className="text-link filter-reset" onClick={() => setActiveFilter('ALL ITEMS')}>{t.allPieces} <ArrowRight size={15} /></button></div>}</section></>;
}
