import { ArrowRight } from 'lucide-react';
import { heroImages } from '../data';
import { useI18n } from '../i18n';

const podcastUrl = 'https://www.ivoox.com/en/podcast-aderiva-indierock_sq_f11233631_1.html';
const episodes = [
  { num: '150', title: 'The BEATLES — Different songs, not so well known but with musical value', url: 'https://www.ivoox.com/en/aderiva-150-thebeatles-diferentes-canciones-no-tan-conocidas-pero-que-audios-mp3_rf_177177135_1.html', embed: 'https://www.ivoox.com/player_ej_177177135_6_1.html?c1=a5241f' },
  { num: '149', title: 'MADCOOL 2026 — The Last Dinner Party, War on Drugs, Foo Fighters, Interpol, Pixies and more', url: 'https://www.ivoox.com/en/aderiva-149-madcool2026-lastdinnerparty-warondrugs-foofighters-interpol-pixies-kol-reytons-vaccines-pulp-audios-mp3_rf_175497097_1.html', embed: 'https://www.ivoox.com/player_ej_175497097_6_1.html?c1=a5241f' },
  { num: '148', title: 'SUBTERFUGE Records — Los Planetas, Australian Blonde, Dover, Corizonas, Neuman and more', url: 'https://www.ivoox.com/en/aderiva-148-subterfuge-records-losplanetas-australianblonde-dover-corizonas-neuman-vivasuecia-levitants-ninapolaca-audios-mp3_rf_175073485_1.html', embed: 'https://www.ivoox.com/player_ej_175073485_6_1.html?c1=a5241f' },
];
const copy = { EN: { title: 'Alternative Indie Rock', em: 'and more.', text: 'Never ending inspiration. In your headphones, car or speaker.', episodes: 'EPISODES', latest: 'Latest', all: 'SEE ALL EPISODES' }, ES: { title: 'Alternative Indie Rock', em: 'y mucho más.', text: 'Inspiración sin fin. En tus auriculares, coche o altavoz.', episodes: 'EPISODIOS', latest: 'Últimos', all: 'VER TODOS LOS EPISODIOS' }, FR: { title: 'Alternative Indie Rock', em: 'et bien plus.', text: 'Une inspiration sans fin. Dans vos écouteurs, votre voiture ou votre enceinte.', episodes: 'ÉPISODES', latest: 'Derniers', all: 'VOIR TOUS LES ÉPISODES' }, DE: { title: 'Alternative Indie Rock', em: 'und mehr.', text: 'Endlose Inspiration. In deinen Kopfhörern, im Auto oder über den Lautsprecher.', episodes: 'EPISODEN', latest: 'Neueste', all: 'ALLE EPISODEN ANSEHEN' } } as const;

export function Podcast() {
  const { language } = useI18n(); const c = copy[language];
  return <><style>{`.podcast-episodes .episode-list{display:flex;flex-direction:column;gap:clamp(42px,7vw,90px)}.podcast-episodes .episode{display:grid;grid-template-columns:minmax(0,1fr) minmax(420px,1fr);align-items:center;gap:clamp(28px,6vw,90px);position:relative;min-height:230px}.podcast-episodes .episode.player-first .episode-info{order:2}.podcast-episodes .episode.player-first .ivoox-player{order:1}.podcast-episodes .episode-num{position:absolute;left:-28px;top:-20px;font-size:clamp(42px,6vw,72px);font-weight:900;color:#a5241f;line-height:1;z-index:2}.podcast-episodes .episode-info h3{margin:0 0 12px}.podcast-episodes .ivoox-player{width:100%;min-width:0;overflow:visible;display:block;position:relative;z-index:1}.podcast-episodes .ivoox-player iframe{display:block;width:100%;height:210px;min-height:210px;border:0;overflow:hidden}.podcast-episodes .episode:nth-child(even){transform:translateX(2vw)}.podcast-episodes .episode:nth-child(odd){transform:translateX(-1vw)}@media(max-width:900px){.podcast-episodes .episode{grid-template-columns:1fr;gap:22px;min-height:0}.podcast-episodes .episode.player-first .episode-info,.podcast-episodes .episode.player-first .ivoox-player{order:initial}.podcast-episodes .episode:nth-child(even),.podcast-episodes .episode:nth-child(odd){transform:none}.podcast-episodes .episode-num{left:0;top:-28px}.podcast-episodes .ivoox-player iframe{height:210px;min-height:210px}}`}</style><section className="podcast-section podcast-page-hero" style={{ backgroundImage: `url(${heroImages.vinyl})` }}><div className="podcast-hero-overlay" /><div className="podcast-art"><div className="record"><div className="record-label">AD<br />FM</div></div></div><div className="podcast-copy"><p className="eyebrow">AD/FM — THE ADERIVA PODCAST</p><h2>{c.title}<br /><em>{c.em}</em></h2><p>{c.text}</p></div></section><section className="shop-section podcast-episodes"><div className="section-heading"><div><p className="eyebrow">{c.episodes}</p><h2>{c.latest} <em>{c.episodes.toLowerCase()}.</em></h2></div></div><div className="episode-list">{episodes.map((episode, index) => <article key={episode.num} className={`episode episode-${index % 2 === 0 ? 'text-first' : 'player-first'}`}><span className="episode-num">{episode.num}</span><div className="episode-info"><a href={episode.url} target="_blank" rel="noreferrer"><h3>{episode.title}</h3></a><p>ADeriva. IndieRock.</p></div><div className="ivoox-player"><iframe title={`ADeriva episode ${episode.num} player`} src={episode.embed} loading="lazy" allow="autoplay; encrypted-media" scrolling="no" frameBorder="0" /></div></article>)}</div><a className="podcast-all-button" href={podcastUrl} target="_blank" rel="noreferrer">{c.all} <ArrowRight size={15} /></a></section></>;
}
