const RSS_URL = 'https://feeds.ivoox.com/feed_fg_f11233631_filtro_1.xml';
const OUTPUT = 'src/data/podcastEpisodes.ts';
const MAX_EPISODES = 3;

const response = await fetch(RSS_URL, { headers: { 'User-Agent': 'ADeriva-Podcast-Updater/1.0' } });
if (!response.ok) throw new Error(`iVoox RSS request failed: ${response.status}`);
const xml = await response.text();

function value(block, tag) {
  const re = new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, 'i');
  const match = block.match(re);
  if (!match) return '';
  return decodeXml(match[1].replace(/<!\[CDATA\[/g, '').replace(/\]\]>/g, '').trim());
}

function decodeXml(text) {
  return text
    .replace(/&#(\\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)))
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'");
}

function episodeNumber(title, link) {
  const match = `${title} ${link}`.match(/(?:aderiva|adfm)[^0-9]{0,8}(\\d{1,4})/i) || link.match(/(?:^|[-_])([0-9]{2,4})(?:[-_]|\.|$)/);
  return match ? match[1] : '';
}

function ivooxId(link) {
  const match = link.match(/(?:rf_|ej_)(\\d+)/i);
  return match ? match[1] : '';
}

const items = [...xml.matchAll(/<item(?:\\s[^>]*)?>([\\s\\S]*?)</item>/gi)]
  .map(m => m[1])
  .map(block => {
    const title = value(block, 'title');
    const link = value(block, 'link') || value(block, 'guid');
    const pubDate = value(block, 'pubDate');
    const id = ivooxId(link) || ivooxId(value(block, 'guid'));
    const num = episodeNumber(title, link);
    if (!title || !link || !id || !num) return null;
    return {
      num,
      title,
      url: link,
      embed: `https://www.ivoox.com/player_ej_${id}_6_1.html?c1=a5241f`,
      pubDate: Date.parse(pubDate) || 0,
    };
  })
  .filter(Boolean)
  .sort((a, b) => b.pubDate - a.pubDate)
  .slice(0, MAX_EPISODES)
  .map(({ pubDate, ...episode }) => episode);

if (!items.length) throw new Error('No valid iVoox episodes found in RSS feed.');

const output = `// AUTO-GENERATED by scripts/update-podcast.mjs — do not edit manually.\nimport type { PodcastEpisode } from '../components/Layout';\n\nexport const episodes: PodcastEpisode[] = ${JSON.stringify(items, null, 2)};\n`;

const fs = await import('node:fs/promises');
const current = await fs.readFile(OUTPUT, 'utf8').catch(() => '');
if (current !== output) {
  await fs.writeFile(OUTPUT, output, 'utf8');
  console.log(`Updated ${OUTPUT} with ${items.length} latest episodes.`);
} else {
  console.log('Podcast data is already up to date.');
}
