// AUTO-GENERATED by scripts/update-podcast.mjs — do not edit manually.
import type { PodcastEpisode } from '../components/Layout';

export const episodes: PodcastEpisode[] = [
  { num: '150', title: 'The BEATLES — Different songs, not so well known but with musical value', url: 'https://www.ivoox.com/en/aderiva-150-thebeatles-diferentes-canciones-no-tan-conocidas-pero-que-audios-mp3_rf_177177135_1.html', embed: 'https://www.ivoox.com/player_ej_177177135_6_1.html?c1=a5241f' },
  { num: '149', title: 'MADCOOL 2026 — The Last Dinner Party, War on Drugs, Foo Fighters, Interpol, Pixies and more', url: 'https://www.ivoox.com/en/aderiva-149-madcool2026-lastdinnerparty-warondrugs-foofighters-interpol-pixies-kol-reytons-vaccines-pulp-audios-mp3_rf_175497097_1.html', embed: 'https://www.ivoox.com/player_ej_175497097_6_1.html?c1=a5241f' },
  { num: '148', title: 'SUBTERFUGE Records — Los Planetas, Australian Blonde, Dover, Corizonas, Neuman and more', url: 'https://www.ivoox.com/en/aderiva-148-subterfuge-records-losplanetas-australianblonde-dover-corizonas-neuman-vivasuecia-levitants-ninapolaca-audios-mp3_rf_175073485_1.html', embed: 'https://www.ivoox.com/player_ej_175073485_6_1.html?c1=a5241f' },
];
